function [traj, infStates] = ehgf_binary_pu_tbt(r, p, varargin)
% Enhanced HGF for binary inputs with trial-by-trial perceptual uncertainty.
%
% This is a backward-compatible wrapper that calls hgf_binary_pu_tbt_unified
% with update_type = 'ehgf'. Uses a safe precision update that prevents negative precision values.
%
% For detailed documentation of inputs, outputs, and the update equations,
% see hgf_binary_pu_tbt_unified.m.
%
% This function can be called in two ways:
% (1) ehgf_binary_pu_tbt(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) ehgf_binary_pu_tbt(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'ehgf';

[traj, infStates] = hgf_binary_pu_tbt_unified(r, p, varargin{:});

end
