function [traj, infStates] = ehgf_jget(r, p, varargin)
% Enhanced HGF for the jumping Gaussian estimation task (JGET).
%
% This is a backward-compatible wrapper that calls hgf_jget_unified
% with update_type = 'ehgf'. Uses a safe precision update that prevents negative precision values.
%
% For detailed documentation of inputs, outputs, and the update equations,
% see hgf_jget_unified.m.
%
% This function can be called in two ways:
% (1) ehgf_jget(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) ehgf_jget(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'ehgf';

[traj, infStates] = hgf_jget_unified(r, p, varargin{:});

end
