function [traj, infStates] = hgf(r, p, varargin)
% Standard Hierarchical Gaussian Filter for continuous inputs.
%
% This is a backward-compatible wrapper that calls hgf_unified
% with update_type = 'hgf'.
%
% This function can be called in two ways:
% (1) hgf(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) hgf(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'hgf';

[traj, infStates] = hgf_unified(r, p, varargin{:});

end
