function [traj, infStates] = hgf_jget(r, p, varargin)
% Calculates the trajectories of the agent's representations under the HGF model
% of the jumping Gaussian estimation task (JGET).
%
% This is a backward-compatible wrapper that calls hgf_jget_unified
% with update_type = 'hgf'.
%
% This function can be called in two ways:
% (1) hgf_jget(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) hgf_jget(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'hgf';

[traj, infStates] = hgf_jget_unified(r, p, varargin{:});

end
