function t = hgf_time_axis(r, n)
% Extracts the time axis from the input structure.
%
% Handles both regular and irregular intervals. For irregular intervals,
% the last column of the input matrix r.u must contain the inter-trial
% intervals, and r.c_prc.irregular_intervals must be set to true.
%
% INPUT:
%   r   Structure generated by fitModel (contains r.u, r.c_prc)
%   n   Total number of trials including dummy zeroth trial
%
% OUTPUT:
%   t   Column vector of time intervals [n x 1]

try
    if r.c_prc.irregular_intervals
        if size(r.u, 2) > 1
            t = [0; r.u(:,end)];
        else
            error('tapas:hgf:InputSingleColumn', ...
                'Input matrix must contain more than one column if irregular_intervals is set to true.');
        end
    else
        t = ones(n,1);
    end
catch
    if size(r.u, 2) > 1
        t = [0; r.u(:,end)];
    else
        t = ones(n,1);
    end
end

end
