function [traj, infStates] = hgf_binary_pu(r, p, varargin)
% Calculates the trajectories of the agent's representations under the HGF
% for binary inputs with perceptual uncertainty.
%
% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is a backward-compatible wrapper that calls hgf_binary% This is award-compatible wrapper that calls hgf_binary_pu_unified
% with update_type = 'ehgf'.
%
% This function can be called in two ways:
% (1) ehgf_binary_pu(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) ehgf_binary_pu(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'ehgf';

[traj, infStates] = hgf_binary_pu_unified(r, p, varargin{:});

end
