function [traj, infStates] = ehgf_ar1_binary_mab(r, p, varargin)
% Enhanced HGF for AR(1) processes with binary outcomes in a multi-armed bandit.
%
% This is a backward-compatible wrapper that calls hgf_ar1_binary_mab_unified
% with update_type = 'ehgf'. Uses a safe precision update. Extends AR(1) binary HGF to multi-armed
%   bandit settings.
%
% For detailed documentation of inputs, outputs, and the update equations,
% see hgf_ar1_binary_mab_unified.m.
%
% This function can be called in two ways:
% (1) ehgf_ar1_binary_mab(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) ehgf_ar1_binary_mab(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'ehgf';

[traj, infStates] = hgf_ar1_binary_mab_unified(r, p, varargin{:});

end
