function [traj, infStates] = hgf_ar1_binary(r, p, varargin)
% Standard HGF for AR(1) processes with binary outcomes.
%
% This is a backward-compatible wrapper that calls hgf_ar1_binary_unified
% with update_type = 'hgf'. Uses the classic precision update equations. Includes drift (rho) and
%   mean-reversion (phi, m) parameters.
%
% For detailed documentation of inputs, outputs, and the update equations,
% see hgf_ar1_binary_unified.m.
%
% This function can be called in two ways:
% (1) hgf_ar1_binary(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) hgf_ar1_binary(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'hgf';

[traj, infStates] = hgf_ar1_binary_unified(r, p, varargin{:});

end
