function [traj, infStates] = hgf_unified(r, p, varargin)
% Unified Hierarchical Gaussian Filter for continuous inputs.
%
% This function implements both the standard HGF and the enhanced HGF (eHGF)
% for continuous inputs with n levels. The update type is controlled by the
% configuration setting r.c_prc.update_type:
%   'hgf'  - Standard HGF (Mathys et al., 2011)
%   'ehgf' - Enhanced HGF (safe precision updates, prevents negative precision)
%
% This function can be called in two ways:
% (1) hgf_unified(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) hgf_unified(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

% Determine update type from config
try
    update_type = r.c_prc.update_type;
catch
    update_type = 'ehgf'; % Default to safe variant
end

% Transform parameters back to their native space if needed
if ~isempty(varargin) && strcmp(varargin{1},'trans')
    if strcmp(update_type, 'hgf')
        p = hgf_transp(r, p);
    else
        p = ehgf_transp(r, p);
    end
end

% Number of levels
l = length(p)/5;

if l ~= floor(l)
    error('tapas:hgf:UndetNumLevels', 'Cannot determine number of levels');
end

% Unpack parameters
mu_0 = p(1:l);
sa_0 = p(l+1:2*l);
rho  = p(2*l+1:3*l);
ka   = p(3*l+1:4*l-1);
om   = p(4*l:5*l-2);
th   = exp(p(5*l-1));
al   = 1/p(5*l);

% Add dummy "zeroth" trial
u = [0; r.u(:,1)];

% Number of trials (including prior)
n = length(u);

% Get time axis
t = hgf_time_axis(r, n);

% Initialize updated quantities
mu    = NaN(n,l);
pi    = NaN(n,l);
muhat = NaN(n,l);
pihat = NaN(n,l);
v     = NaN(n,l);
w     = NaN(n,l-1);
da    = NaN(n,l);
dau   = NaN(n,1);

% Representation priors
mu(1,:) = mu_0;
pi(1,:) = 1./sa_0;

% Representation update loop
for k = 2:1:n
    if not(ismember(k-1, r.ign))

        %%%%%%%%%%%%%%%%%%%%%%
        % Effect of input u(k)
        %%%%%%%%%%%%%%%%%%%%%%

        % 1st level
        % ~~~~~~~~~
        muhat(k,1) = hgf_prediction(mu(k-1,1), t(k), 'rho', rho(1));
        pihat(k,1) = hgf_pihat(pi(k-1,1), t(k), ka(1), mu(k-1,2), om(1));
        [pi(k,1), mu(k,1), dau(k), da(k,1)] = hgf_continuous_level1(u(k), muhat(k,1), pihat(k,1), al);

        if l > 2
            % Pass through higher levels
            % ~~~~~~~~~~~~~~~~~~~~~~~~~~
            for j = 2:l-1
                muhat(k,j) = hgf_prediction(mu(k-1,j), t(k), 'rho', rho(j));
                pihat(k,j) = hgf_pihat(pi(k-1,j), t(k), ka(j), mu(k-1,j+1), om(j));

                [pi(k,j), mu(k,j), v(k,j-1), w(k,j-1)] = hgf_volatility_update(...
                    muhat(k,j), pihat(k,j), ...
                    ka(j-1), pihat(k,j-1), da(k,j-1), ...
                    mu(k-1,j), om(j-1), pi(k-1,j-1), ...
                    pi(k,j-1), mu(k,j-1), muhat(k,j-1), t(k), update_type);

                da(k,j) = hgf_volatility_pe(pi(k,j), mu(k,j), muhat(k,j), pihat(k,j));
            end
        end

        % Last level
        % ~~~~~~~~~~
        muhat(k,l) = hgf_prediction(mu(k-1,l), t(k), 'rho', rho(l));
        pihat(k,l) = hgf_pihat_last(pi(k-1,l), t(k), th);

        % Weighting factor and v for last level
        v(k,l)   = t(k) * th;
        v(k,l-1) = t(k) * exp(ka(l-1) * mu(k-1,l) + om(l-1));

        [pi(k,l), mu(k,l), ~, w(k,l-1)] = hgf_volatility_update(...
            muhat(k,l), pihat(k,l), ...
            ka(l-1), pihat(k,l-1), da(k,l-1), ...
            mu(k-1,l), om(l-1), pi(k-1,l-1), ...
            pi(k,l-1), mu(k,l-1), muhat(k,l-1), t(k), update_type);

        da(k,l) = hgf_volatility_pe(pi(k,l), mu(k,l), muhat(k,l), pihat(k,l));
    else
        mu(k,:) = mu(k-1,:);
        pi(k,:) = pi(k-1,:);
        muhat(k,:) = muhat(k-1,:);
        pihat(k,:) = pihat(k-1,:);
        v(k,:)  = v(k-1,:);
        w(k,:)  = w(k-1,:);
        da(k,:) = da(k-1,:);
    end
end

% Remove representation priors
mu(1,:) = [];
pi(1,:) = [];

% Check validity of trajectories (standard HGF only)
if strcmp(update_type, 'hgf')
    hgf_check_trajectories(mu, pi, 256, []);
end

% Remove other dummy initial values
muhat(1,:) = [];
pihat(1,:) = [];
v(1,:)     = [];
w(1,:)     = [];
da(1,:)    = [];
dau(1)     = [];

% Create result data structure
traj = struct;
traj.mu     = mu;
traj.sa     = 1./pi;
traj.muhat  = muhat;
traj.sahat  = 1./pihat;
traj.v      = v;
traj.w      = w;
traj.da     = da;
traj.dau    = dau;

% Updates with respect to prediction
traj.ud = mu - muhat;

% Psi (precision weights on prediction errors)
psi        = NaN(n-1,l);
psi(:,1)   = 1./(al*pi(:,1));
psi(:,2:l) = pihat(:,1:l-1)./pi(:,2:l);
traj.psi   = psi;

% Epsilons (precision-weighted prediction errors)
epsi        = NaN(n-1,l);
epsi(:,1)   = psi(:,1) .* dau;
epsi(:,2:l) = psi(:,2:l) .* da(:,1:l-1);
traj.epsi   = epsi;

% Full learning rate (full weights on prediction errors)
wt        = NaN(n-1,l);
wt(:,1)   = psi(:,1);
wt(:,2:l) = 1/2 * (v(:,1:l-1) * diag(ka(1:l-1))) .* psi(:,2:l);
traj.wt   = wt;

% Create matrices for use by the observation model
infStates = NaN(n-1,l,4);
infStates(:,:,1) = traj.muhat;
infStates(:,:,2) = traj.sahat;
infStates(:,:,3) = traj.mu;
infStates(:,:,4) = traj.sa;

end
