function [traj, infStates] = uhgf_binary(r, p, varargin)
% Unbounded Hierarchical Gaussian Filter for binary inputs.
%
% This is a backward-compatible wrapper that calls hgf_binary_unified
% with update_type = 'uhgf'. Uses a dual quadratic approximation with
% sigmoid-based interpolation for the volatility update.
%
% For detailed documentation of inputs, outputs, and the update equations,
% see hgf_binary_unified.m.
%
% This function can be called in two ways:
% (1) uhgf_binary(r, p)
%     where r is the structure generated by fitModel and p is the parameter vector in native space;
% (2) uhgf_binary(r, ptrans, 'trans')
%     where r is the structure generated by fitModel, ptrans is the parameter vector in
%     transformed space, and 'trans' is a flag indicating this.

r.c_prc.update_type = 'uhgf';

[traj, infStates] = hgf_binary_unified(r, p, varargin{:});

end
